general:
  description: na

input_data:

  gsp:
    zarr_path: /mnt/disks/uk_all_inputs_v2/pv_gsp/pvlive_gsp.zarr
    interval_start_minutes: -120
    interval_end_minutes: 480
    time_resolution_minutes: 30
    # A random value from the list below will be chosen as the delay when dropout is used
    # If set to null no dropout is applied. Only values before t0 are dropped out for GSP.
    # Values after t0 are assumed as targets and cannot be dropped.
    dropout_timedeltas_minutes: []
    dropout_fraction: 0 # Fraction of samples with dropout


  solar_position:
    interval_start_minutes: -120
    interval_end_minutes: 480
    time_resolution_minutes: 30


  nwp:
  
    ukv:
        provider: ukv
        zarr_path: /mnt/disks/uk_all_inputs_v2/nwp/ukv/UKV_v7/UKV_2022.zarr
        interval_start_minutes: -120
        interval_end_minutes: 480
        time_resolution_minutes: 60

        image_size_pixels_height: 24
        image_size_pixels_width: 24
        dropout_timedeltas_minutes: [-180]
        dropout_fraction: 1.0
        max_staleness_minutes: null

        channels:
        # These variables exist in the CEDA training set and in the live MetOffice live service
        - t # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - sde # snow depth water equivalent
        - r # relative humidty
        - vis # visibility
        - si10 # 10-metre wind speed
        - prate # precipitation rate

        normalisation_constants:
          t:
            mean: 283.64913206
            std: 4.38818501
          dswrf:
            mean: 111.28265039
            std: 190.47216887
          dlwrf:
            mean: 325.03130139
            std: 39.45988077
          hcc:
            mean: 29.11949682
            std: 38.07184418
          mcc:
            mean: 40.88984494
            std: 41.91144559
          lcc:
            mean: 50.08362643
            std: 39.33210726
          sde:
            mean: 0.00289545
            std: 0.1029753
          r:
            mean: 81.79229501
            std: 11.45012499
          vis:
            mean: 32262.03285118
            std: 21578.97975625
          si10:
            mean: 6.88348448
            std: 3.94718813
          prate:
            mean: 0.0000345793433
            std: 0.00021497
        
    ecmwf:
        provider: ecmwf
        zarr_path: /mnt/disks/uk_all_inputs_v2/nwp/ecmwf/UK_v3/ECMWF_2022.zarr
        interval_start_minutes: -120
        interval_end_minutes: 480
        time_resolution_minutes: 60

        image_size_pixels_height: 12 # roughly equivalent to ukv 48
        image_size_pixels_width: 12 # roughly equivalent to ukv 48
        dropout_timedeltas_minutes: [-360]
        dropout_fraction: 1.0
        max_staleness_minutes: null
        
        channels:
        - t2m # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - tcc # total cloud cover
        - sd # snow depth water equivalent
        - sr # direct solar radiation
        - duvrs # downwards UV radiation at surface
        - u10 # 10-metre U component of wind speed
        - v10 # 10-metre V component of wind speed
        
        # The following channels are accumulated and need to be diffed
        accum_channels:
        - dswrf
        - dlwrf
        - sr
        - duvrs

        normalisation_constants:
          t2m:
            mean: 283.48333740234375
            std: 3.692270040512085
          diff_dswrf:
            mean: 420584.6875
            std: 715366.3125
          diff_dlwrf:
            mean: 1136464.0
            std: 131942.03125
          hcc:
            mean: 0.3961029052734375
            std: 0.42244860529899597
          mcc:
            mean: 0.3288780450820923
            std: 0.38039860129356384
          lcc:
            mean: 0.44901806116104126
            std: 0.3791404366493225
          tcc:
            mean: 0.7049227356910706
            std: 0.37487083673477173
          sd:
            mean: 0.00008107526082312688
            std: 0.000913831521756947
          diff_sr:
            mean: 469169.5
            std: 818950.6875
          diff_duvrs:
            mean: 48265.4765625
            std: 81605.25
          u10:
            mean: 1.7677178382873535
            std: 5.531515598297119
          v10:
            mean: 0.985887885093689
            std: 5.411230564117432

  satellite:
    zarr_path: /mnt/disks/uk_all_inputs_v2/sat/2022_nonhrv.zarr
    interval_start_minutes: -60
    interval_end_minutes: 0
    time_resolution_minutes: 5

    image_size_pixels_height: 24
    image_size_pixels_width: 24
    dropout_timedeltas_minutes: []
    dropout_fraction: 0.

    channels:
      - IR_016
      - IR_039
      - IR_087
      - IR_097
      - IR_108
      - IR_120
      - IR_134
      - VIS006
      - VIS008
      - WV_062
      - WV_073

    normalisation_constants:
      IR_016:
        mean: 0.17594202
        std: 0.21462157
      IR_039:
        mean: 0.86167645
        std: 0.04618041
      IR_087:
        mean: 0.7719318
        std: 0.06687243
      IR_097:
        mean: 0.8014212
        std: 0.0468558
      IR_108:
        mean: 0.71254843
        std: 0.17482725
      IR_120:
        mean: 0.89058584
        std: 0.06115861
      IR_134:
        mean: 0.944365
        std: 0.04492306
      VIS006:
        mean: 0.09633306
        std: 0.12184761
      VIS008:
        mean: 0.11426069
        std: 0.13090034
      WV_062:
        mean: 0.7359355
        std: 0.16111417
      WV_073:
        mean: 0.62479186
        std: 0.12924142