name: Pull CI (Python)
run-name: 'Test PR edit #${{ github.event.number }} "${{ github.event.pull_request.title }}"'

on:
  pull_request:
    types: [opened, edited, reopened]
    paths-ignore: ['README.md']

jobs:

  echo:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.pull_request.head.repo.name }}
      REPOSITORY_NAME: ${{ github.repository }}
    steps:
      - name: Echo variables
        run: echo "$REPO_NAME" "$REPOSITORY_NAME"

  pull-ci:
    uses: openclimatefix/.github/.github/workflows/branch_ci.yml@main
    if: ${{ github.event.pull_request.head.repo.name != github.repository }}
    with:
      enable_linting: true
      enable_typechecking: false
      containerfile: 'None'
      tests_folder: 'tests'
      tests_matrix: true
